### ISSUE TITLE
Ошибка при запуске скрипта (Ошибка tinvest.exceptions.UnexpectedError: 500 )

### ISSUE THREAD

**Issue by Kloblok** [Tinkoff/invest-openapi#687]
Traceback (most recent call last):
  File "/home/user/Desktop/bot/v2/tb2.1.py", line 104, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/user/Desktop/bot/v2/tb2.1.py", line 44, in main
    await client.register_sandbox_account(SandboxRegisterRequest(broker_account_type=BrokerAccountType.tinkoff))
  File "/usr/local/lib/python3.10/dist-packages/tinvest/clients.py", line 134, in register_sandbox_account
    return await sandbox_register_post(self._request, body)
  File "/usr/local/lib/python3.10/dist-packages/tinvest/clients.py", line 117, in _request
    raise UnexpectedError(response.status, await response.text())
tinvest.exceptions.UnexpectedError: 500 

14.06 код работал исправно, 15.06 код начал выдавать ошибку указанную выше. Изменения не вносились. Ошибка tinvest.exceptions.UnexpectedError: 500 указывает на внутреннюю ошибку на стороне сервера при обработке запроса к API брокера Tinkoff. Посчитал, что ошибка может быть вызвана конфликтом библиотек, установленных после последнего удачного запуска кода. Удалил их. Ошибка не пропала. Помогите, пожалуйста

**Comment by KirillKaverin** [comment]
Api V1 вырубили. Переходите на V2. Для перехода было достаточно времени (больше года) и есть пакеты под Python.
